checker_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Calib_data/Checkerboard_calib_cam/'
save_camera_params_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Save_data/camera_params.yml'
save_calib_handeye  =  'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Save_data/calib_handeye.yml'
R_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Calib_data/handeye/R.txt'
t_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Calib_data/handeye/t.txt'
Checkerboard_calib_laser_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Calib_data/Checkerboard_calib_laser/'
Laser_position_output_path = 'C:/Users/ASUS/Desktop/THINKALPHA/233/NCKH/laser-vision/Output/Laser_position_output/'